# Starter template for:
# Deploying the solution to a validation environment
# Deployment is triggered by build completion so no trigger or pr should be specified
trigger: none
pr: none
resources:
  repositories:
  - repository: PipelineRepo  # repository name (DO NOT CHANGE THIS VALUE) 
    type: github
    ref: main # If your pipeline templates are in a branch other than the default branch specify the branch here. Otherwise the default branch will be used by default.
    endpoint: powercat-alm # Specifies the GitHub service connection for this setup.
    name: Microsoft/coe-alm-accelerator-templates  #This is the name of the repo in the current project in Azure Devops that has the pipeline templates. If the repo is in a different project you can specify the project and repo using the format ProjectContainingTheBuildTemplates/RepositoryContainingTheBuildTemplates (https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#type)
  pipelines: # The pipelines specify which pipeline this pipeline will pull artifacts from. In this case we will deploy from the test build's artifacts
    - pipeline: buildPipeline  # pipeline name (DO NOT CHANGE THIS VALUE) 
      source: deploy-test-CenterofExcellenceALMAccelerator # This is the name of the build pipeline that contains the artifacts to be deployed by this pipeline. NOTE: There must be a successful build for this pipeline available in order to run this pipeline

# NOTE: If you want to use different values for these variables, you can remove the variable group and attach them directly to this pipeline. The group specified below is a variable group defined in the Library for the Pipelines
variables:
- group: alm-accelerator-variable-group
- name: SolutionName # variable Name  (DO NOT CHANGE THIS VALUE) 
  value: 'CenterofExcellenceALMAccelerator' #Replace with the actual name of the solution you are building. (NOTE: Not the Display Name)

stages:
- template: Pipelines\Templates\deploy-Solution-To-Environment.yml@PipelineRepo