EnvironmentTypeInfo As CanvasComponent:
    Fill: =RGBA(0, 0, 0, 0)
    Height: =220
    IsVisible: =var_visible
    OnReset: =If( Self.Show = true, Set(var_visible, true), Set(var_visible, false))
    Show: =false
    Text: |-
        ="Choose production type if you're ready to deploy. If you're still developing or testing, choose Sandbox for a non-production environment. Learn more about environment types in <a href='https://go.microsoft.com/fwlink/?linkid=2093069' style='color:purple;'>this overview</a>."
    Width: =500
    X: =0
    Y: =0
    ZIndex: =1

    HtmlText3 As htmlViewer:
        Height: =246
        HtmlText: |-
            ="<div style='
                margin: 30px;
                height:150px;
                width:400px;
                background:white;
                box-shadow: 0px 0px 10px rgba(0,0,0,0.1);
            '></div>"
        Width: =500
        ZIndex: =1

    HtmlText2 As htmlViewer:
        Font: =Font.'Segoe UI'
        Height: =103
        HtmlText: =EnvironmentTypeInfo.Text
        Width: =376
        X: =51
        Y: =68
        ZIndex: =2

    Icon11 As icon.Cancel:
        BorderColor: =RGBA(166, 166, 166, 1)
        Color: =Purple
        DisabledBorderColor: =RGBA(0, 0, 0, 0)
        DisabledColor: =RGBA(220, 220, 220, 1)
        DisabledFill: =RGBA(0, 0, 0, 0)
        FocusedBorderThickness: =4
        Height: =19
        HoverBorderColor: =RGBA(0, 0, 0, 0)
        HoverColor: =ColorFade(RGBA(105, 121, 126, 1), -30%)
        HoverFill: =RGBA(0, 0, 0, 0)
        Icon: =Icon.Cancel
        OnSelect: =Set( var_visible, true ); Set( var_visible, false )
        PressedBorderColor: =RGBA(0, 0, 0, 0)
        PressedColor: =ColorFade(RGBA(105, 121, 126, 1), -30%)
        PressedFill: =RGBA(0, 0, 0, 0)
        Width: =30
        X: =390
        Y: =44
        ZIndex: =3

