DeploymentHistoryScreen As screen:
    BackgroundImage: =
    Height: =Max(App.Height, App.DesignHeight)
    OnVisible: =
    Width: =Max(App.Width, App.DesignWidth)

    SearchHistoryBox As group:
        Height: =5
        Width: =5
        X: =40
        Y: =40
        ZIndex: =12

        txtHistorySearch As text:
            AccessibleLabel: ="Search History"
            Clear: =false
            Default: =SolutionHistorySearchText
            DelayOutput: =true
            Height: =46
            HintText: ="Search History"
            HoverBorderColor: =ColorFade(txtHistorySearch.BorderColor, 20%)
            HoverColor: =ColorFade(txtHistorySearch.Color, 20%)
            HoverFill: =ColorFade(txtHistorySearch.Fill, 20%)
            OnSelect: =
            PaddingLeft: =10
            PressedBorderColor: =txtHistorySearch.HoverBorderColor
            PressedColor: =txtHistorySearch.Color
            PressedFill: =txtHistorySearch.Fill
            Width: =364
            X: =1532
            Y: =90
            ZIndex: =19

        icoHistorySearch As icon.Search:
            AccessibleLabel: ="Search Solutions"
            BorderColor: =ColorFade(icoHistorySearch.Fill, -20%)
            Color: =PrimaryColor2Value
            DisabledFill: =ColorFade(icoHistorySearch.Fill, -80%)
            Height: =43
            HoverBorderColor: =ColorFade(icoHistorySearch.BorderColor, 20%)
            HoverColor: =ColorFade(icoHistorySearch.Color, 20%)
            HoverFill: =ColorFade(icoHistorySearch.Fill, 20%)
            Icon: =If(Len(txtHistorySearch.Text) = 0, Icon.Search, Icon.Cancel)
            OnSelect: |-
                =If(
                    icoHistorySearch.Icon = Icon.Cancel,
                    Set(
                        SolutionHistorySearchText,
                        ""
                    );
                    Reset(txtHistorySearch)
                )
            PaddingBottom: =10
            PaddingLeft: =10
            PaddingRight: =10
            PaddingTop: =10
            PressedBorderColor: =ColorFade(icoHistorySearch.BorderColor, -20%)
            PressedColor: =ColorFade(icoHistorySearch.Color, -20%)
            PressedFill: =ColorFade(icoHistorySearch.Fill, -20%)
            Width: =51
            X: =1845
            Y: =91
            ZIndex: =21

    lblHistoryTitle As label:
        Align: =Center
        Color: =RGBA(255, 255, 255, 1)
        Fill: =PrimaryColor2Value
        Font: =Font.'Segoe UI'
        FontWeight: =Semibold
        Height: =68
        OnSelect: =
        Size: =20
        Text: ="Power Platform ALM Accelerator Request History"
        Width: =1920
        ZIndex: =16

    "glrDeploymentRequests As gallery.'BrowseLayout_Vertical_TwoTextVariant_ver4.0'":
        AccessibleLabel: ="Solutions"
        Fill: =RGBA(255,255, 255, 1)
        Height: =876
        Items: =Search(Sort(DeploymentRequestHistory, 'Created On', Descending), txtHistorySearch.Text, "DisplayName")
        Layout: =Layout.Vertical
        OnSelect: =
        TemplatePadding: =0
        TemplateSize: =85
        Width: =App.Width - 40
        X: =20
        Y: =182
        ZIndex: =37

        Title2_1 As label:
            Color: =RGBA(0, 0, 0, 1)
            FontWeight: =Normal
            Height: =37
            OnSelect: =
            PaddingBottom: =0
            PaddingLeft: =0
            PaddingRight: =0
            PaddingTop: =0
            Size: =15
            Text: =ThisItem.Name
            Tooltip: =ThisItem.DisplayName
            VerticalAlign: =VerticalAlign.Top
            Width: =530
            Wrap: =false
            X: =13
            Y: =17
            ZIndex: =1

        Separator2_1 As rectangle:
            BorderColor: =ColorFade(Separator2_1.Fill, -20%)
            DisabledFill: =Separator2_1.Fill
            Fill: |-
                =ColorValue("#f4f3f2")
            Height: =1
            HoverFill: =ColorFade(Separator2_1.Fill, 20%)
            OnSelect: =Select(Parent)
            PressedFill: =ColorFade(Separator2_1.Fill, -20%)
            Width: =Parent.TemplateWidth
            Y: =Parent.TemplateHeight - 1
            ZIndex: =2

        Image2_1 As image:
            BorderColor: =ColorFade(Image2_1.Fill, -20%)
            Height: =30
            HoverBorderColor: =ColorFade(Image2_1.BorderColor, 20%)
            HoverFill: =ColorFade(Image2_1.Fill, 20%)
            Image: =ic_fluent_error_circle_24_regular
            OnSelect: =Select(Parent)
            PaddingBottom: =2
            PaddingLeft: =2
            PaddingRight: =2
            PaddingTop: =2
            PressedBorderColor: =ColorFade(Image2_1.BorderColor, -20%)
            PressedFill: =ColorFade(Image2_1.Fill, -20%)
            Tooltip: =
            Visible: |-
                =//CurrentProjects.'Project Status' = 'Project Status'.Failed || CurrentProjects.ErrorType = ErrorType.'Deployment Failed'
                false
            Width: =30
            X: =1472
            Y: =33
            ZIndex: =4

        imgHistoryStatus As image:
            AccessibleLabel: ="Publish Status"
            BorderColor: =ColorFade(imgHistoryStatus.Fill, -20%)
            DisplayMode: =DisplayMode.View
            Height: =46
            HoverBorderColor: =ColorFade(imgHistoryStatus.BorderColor, 20%)
            HoverFill: =ColorFade(imgHistoryStatus.Fill, 20%)
            Image: |-
                =//ExportToGitStatus has two outputs - status and result which are used inter variably. 
                If(
                    ThisItem.RequestType = [@Type].Deploy And !IsBlankOrError(ThisItem.Source),
                    Switch(
                        ThisItem.PullRequestStatus.status,
                        "active",
                        LookUp(
                            StageStatesIcons,
                            state = "notStarted"
                        ).image,
                        "completed",
                        LookUp(
                            StageStatesIcons,
                            state = "succeeded"
                        ).image,
                        "abandoned",
                        LookUp(
                            StageStatesIcons,
                            state = "failed"
                        ).image,
                        LookUp(
                            StageStatesIcons,
                            state = "empty"
                        ).image
                    ),
                    If(
                        !IsBlankOrError(ThisItem.ErrorMessage),
                        LookUp(
                            StageStatesIcons,
                            state = "failed"
                        ).image,
                        With(
                            {
                                gitStatus: ThisItem.BuildStatus.status,
                                gitResult: ThisItem.BuildStatus.result
                            },
                            If(
                                IsBlank(gitStatus),
                                LookUp(
                                    StageStatesIcons,
                                    state = "empty"
                                ).image,
                                If(
                                    gitStatus = "completed",
                                    LookUp(
                                        StageStatesIcons,
                                        state = gitResult
                                    ).image,
                                    LookUp(
                                        StageStatesIcons,
                                        state = gitStatus
                                    ).image
                                )
                            )
                        )
                    )
                )
            OnSelect: =Select(Parent);
            PaddingBottom: =10
            PaddingTop: =10
            PressedBorderColor: =ColorFade(imgHistoryStatus.BorderColor, -20%)
            PressedFill: =ColorFade(imgHistoryStatus.Fill, -20%)
            Tooltip: =
            X: =539
            Y: =8
            ZIndex: =6

        icoLaunchExportBuildUrl_1 As icon.Add:
            AccessibleLabel: ="Open Publish Build"
            BorderColor: =ColorFade(icoLaunchExportBuildUrl_1.Fill, -20%)
            Color: =RGBA(0, 0, 0, 0)
            DisabledFill: =ColorFade(icoLaunchExportBuildUrl_1.Fill, -80%)
            DisplayMode: |-
                =If(
                    IsBlankOrError(DeploymentUserSetting) Or IsBlankOrError(DeploymentUserSetting.'Drillthrough Status') Or DeploymentUserSetting.'Drillthrough Status' = 'A Yes or No boolean'.Allowed,
                    DisplayMode.Edit,
                    DisplayMode.Disabled
                )
            Fill: =RGBA(0, 0, 0, 0)
            Height: =80
            HoverBorderColor: =ColorFade(icoLaunchExportBuildUrl_1.BorderColor, 20%)
            HoverColor: =ColorFade(icoLaunchExportBuildUrl_1.Color, 20%)
            HoverFill: =ColorFade(icoLaunchExportBuildUrl_1.Fill, 20%)
            Icon: =
            OnSelect: |
                =Select(Parent);
                If(
                    ThisItem.RequestType = [@Type].Deploy And !IsBlankOrError(ThisItem.Source),
                    Launch("https://dev.azure.com/" & ThisItem.'Deployment Profile'.Organization & "/" & ThisItem.'Deployment Profile'.Project & "/_git/" & ThisItem.'Deployment Profile'.Repository & "/pullrequest/" & ThisItem.'Build ID'),
                    Launch(ThisItem.BuildStatus._links.web.href)
                );
            PressedBorderColor: =ColorFade(icoLaunchExportBuildUrl_1.BorderColor, -20%)
            PressedColor: =ColorFade(icoLaunchExportBuildUrl_1.Color, -20%)
            PressedFill: =ColorFade(icoLaunchExportBuildUrl_1.Fill, -20%)
            Tooltip: |-
                =If(
                    ThisItem.RequestType = [@Type].Deploy,
                    If(
                        Not IsBlank(ThisItem.PullRequestStatus.creationDate),
                        Concatenate(
                            ThisItem.PullRequestStatus.title,
                            " @ ",
                            Text(
                                DateTimeValue(ThisItem.PullRequestStatus.creationDate),
                                DateTimeFormat.LongDateTime
                            )
                        ),
                        Blank()
                    ),
                    If(
                        Not IsBlank(ThisItem.BuildStatus.buildNumber),
                        Concatenate(
                            Text(ThisItem.BuildStatus.buildNumber),
                            " @ ",
                            Text(
                                DateTimeValue(ThisItem.BuildStatus.startTime),
                                DateTimeFormat.LongDateTime
                            )
                        ),
                        Blank()
                    )
                )
            Width: =62
            X: =554
            ZIndex: =8

        lblHistoryRequestedByValue As label:
            Align: =Align.Center
            Color: =RGBA(0, 0, 0, 1)
            FontWeight: =Normal
            Height: =37
            OnSelect: =
            PaddingBottom: =0
            PaddingLeft: =0
            PaddingRight: =0
            PaddingTop: =0
            Size: =15
            Text: =If(IsBlankOrError(ThisItem.RequestedByName), "System", ThisItem.RequestedByName)
            Tooltip: =ThisItem.'Created By'.'Full Name'
            VerticalAlign: =VerticalAlign.Top
            Width: =200
            Wrap: =false
            X: =818
            Y: =17
            ZIndex: =11

        lblHistoryActionValue As label:
            Align: =Align.Center
            Color: =RGBA(0, 0, 0, 1)
            FontWeight: =Normal
            Height: =37
            OnSelect: =
            PaddingBottom: =0
            PaddingLeft: =0
            PaddingRight: =0
            PaddingTop: =0
            Size: =15
            Text: =Switch( ThisItem.'Request Type', Type.Delete, deleteSolutionLabel, Type.Deploy, deploySolutionLabel, Type.Import, importSolutionLabel, Type.Promote, promoteSolutionLabel, ThisItem.'Request Type' )
            Tooltip: =ThisItem.'Request Type'
            VerticalAlign: =VerticalAlign.Top
            Width: =200
            Wrap: =false
            X: =625
            Y: =17
            ZIndex: =12

        lblHistoryDeploymentProfileSteps As label:
            Align: =Align.Center
            Color: =RGBA(0, 0, 0, 1)
            FontWeight: =Normal
            Height: =29
            LineHeight: =1.6
            OnSelect: =
            PaddingBottom: =0
            PaddingLeft: =0
            PaddingRight: =0
            PaddingTop: =0
            Size: =12
            Text: =If(!IsBlankOrError(ThisItem.'Deployment Profile'), Concat(ThisItem.'Deployment Profile'.'Deployment Steps', Name, " - "), "No Profile Selected")
            Tooltip: |-
                ="Deployment Profile: " & ThisItem.'Deployment Profile'.Name
            Width: =350
            Wrap: =false
            X: =1530
            Y: =46
            ZIndex: =13

        lblHistoryDeploymentProfile As label:
            Align: =Align.Center
            Color: =RGBA(0, 0, 0, 1)
            FontWeight: =Normal
            Height: =37
            OnSelect: =
            PaddingBottom: =0
            PaddingLeft: =0
            PaddingRight: =0
            PaddingTop: =0
            Size: =15
            Text: =If(!IsBlankOrError(ThisItem.'Deployment Profile'), LookUp('Deployment Profiles', 'Deployment Profile' = ThisItem.'Deployment Profile'.'Deployment Profile').Name, "")
            Tooltip: |-
                ="Deployment Profile: " & ThisItem.'Deployment Profile'.Name
            VerticalAlign: =VerticalAlign.Top
            Width: =350
            Wrap: =false
            X: =1530
            Y: =17
            ZIndex: =14

        lblHistoryTargetValue As label:
            Align: =Align.Center
            Color: =RGBA(0, 0, 0, 1)
            FontWeight: =Normal
            Height: =37
            OnSelect: =
            PaddingBottom: =0
            PaddingLeft: =0
            PaddingRight: =0
            PaddingTop: =0
            Size: =15
            Text: =ThisItem.Target
            Tooltip: =ThisItem.Target
            VerticalAlign: =VerticalAlign.Top
            Width: =500
            Wrap: =false
            X: =1023
            Y: =17
            ZIndex: =15

        lblHistoryDeploymentMessages As label:
            Color: =RGBA(255, 0, 0, 1)
            FontWeight: =Normal
            Height: =29
            LineHeight: =1.6
            OnSelect: =
            PaddingBottom: =0
            PaddingLeft: =0
            PaddingRight: =0
            PaddingTop: =0
            Size: =12
            Text: =ThisItem.Message
            Tooltip: =ThisItem.Message
            Width: =1500
            Wrap: =false
            X: =13
            Y: =46
            ZIndex: =16

    icoHistoryDialogClose As icon.Cancel:
        AccessibleLabel: ="Close"
        BorderColor: =ColorFade(icoHistoryDialogClose.Fill, -20%)
        Color: =RGBA(255, 255, 255, 1)
        DisabledFill: =ColorFade(icoHistoryDialogClose.Fill, -80%)
        Height: =55
        HoverBorderColor: =ColorFade(icoHistoryDialogClose.BorderColor, 20%)
        HoverColor: =ColorFade(icoHistoryDialogClose.Color, 20%)
        HoverFill: =ColorFade(icoHistoryDialogClose.Fill, 20%)
        Icon: =Icon.Cancel
        OnSelect: |
            =Navigate(
                Home,
                ScreenTransition.Fade
            );
        PaddingBottom: =10
        PaddingLeft: =10
        PaddingRight: =10
        PaddingTop: =10
        PressedBorderColor: =ColorFade(icoHistoryDialogClose.BorderColor, -20%)
        PressedColor: =ColorFade(icoHistoryDialogClose.Color, -20%)
        PressedFill: =ColorFade(icoHistoryDialogClose.Fill, -20%)
        Width: =55
        X: =1851
        Y: =4
        ZIndex: =38

    btnHistoryFunctions As groupContainer:
        Height: =320
        Visible: =false
        Width: =564
        X: =1
        Y: =760
        ZIndex: =44

        fncHistoryRefreshStatuses As button:
            Height: =50
            HoverBorderColor: =ColorFade(fncHistoryRefreshStatuses.BorderColor, 20%)
            HoverColor: =ColorFade(fncHistoryRefreshStatuses.Color, 20%)
            HoverFill: =ColorFade(fncHistoryRefreshStatuses.Fill, 20%)
            OnSelect: =
            PressedBorderColor: =fncHistoryRefreshStatuses.Fill
            PressedColor: =fncHistoryRefreshStatuses.Fill
            PressedFill: =fncHistoryRefreshStatuses.Color
            Text: ="fncRefreshStatuses"
            Width: =562
            X: =2
            Y: =60
            ZIndex: =6

    lblNoHistory As label:
        Align: =Align.Center
        FontWeight: =FontWeight.Semibold
        Height: =45
        PaddingLeft: =0
        PaddingTop: =0
        Text: ="There's no history available. Check the search criteria and try again."
        Visible: =IsEmpty(glrDeploymentRequests.AllItems)
        Width: =600
        X: =653
        Y: =512
        ZIndex: =46

    lblHistoryRequestedBy As label:
        Align: =Center
        Font: =Font.'Segoe UI'
        FontWeight: =Semibold
        Height: =32
        Size: =10
        Text: ="REQUESTED BY"
        Width: =110
        X: =884
        Y: =146
        ZIndex: =48

    Group1 As group:
        Height: =5
        Width: =5
        X: =40
        Y: =40
        ZIndex: =48

        lblHistorySolution As label:
            Font: =Font.'Segoe UI'
            FontWeight: =Semibold
            Height: =32
            Size: =10
            Text: ="REQUEST"
            Width: =258
            X: =19
            Y: =146
            ZIndex: =39

        lblHistoryStatus As label:
            Align: =Center
            Font: =Font.'Segoe UI'
            FontWeight: =Semibold
            Height: =32
            Size: =10
            Text: ="STATUS"
            Width: =100
            X: =559
            Y: =146
            ZIndex: =41

        lblHistoryAction As label:
            Align: =Center
            Font: =Font.'Segoe UI'
            FontWeight: =Semibold
            Height: =32
            Size: =10
            Text: ="ACTION"
            Width: =100
            X: =695
            Y: =146
            ZIndex: =42

        lblHistoryProfile As label:
            Align: =Center
            Font: =Font.'Segoe UI'
            FontWeight: =Semibold
            Height: =32
            Size: =10
            Text: ="PROFILE"
            Width: =310
            X: =1589
            Y: =146
            ZIndex: =45

        lblHistoryTarget As label:
            Align: =Center
            Font: =Font.'Segoe UI'
            FontWeight: =Semibold
            Height: =32
            Size: =10
            Text: ="DESTINATION"
            X: =1216
            Y: =146
            ZIndex: =47

