graph
    AA4M((ALM Accelerator <br/> For Makers))
    Maker --> AA4M
    
    subgraph impact[Impact to ALM Paths]
        I{Business <br/> Impact}
        I --> Critical
        I --> High
        I --> NC(Non Critical)

        300(Level 300) --> I
        400(Level 400) --> I
        500(Level 500) --> I
    end

    AA4M2((ALM Accelerator <br/> For Makers))
    NC --> AA4M2

    style impact fill:transparent,stroke:red,stroke-width:2px

    subgraph persona[Persona to ALM Paths]
        C{Creator}
        C --> Maker
        C --> AM(Advanced Maker)
        C --> Developer       
        C --> Operations
        C --> Support       
    end

    style persona fill:transparent,stroke:orange,stroke-width:2px

    hideComplexity(Hides Complexity)
    
    AA4M -.-> hideComplexity
    
    subgraph aa4am[Paths to ALM Accelerator For Advanced Makers]
    prereqInstalled{Prerequisites <br/> Installed?}
        prereqInstalled --> prereqYes(Yes)
        prereqInstalled --> prereqNo(No)
        
        AM --> prereqInstalled
        Developer --> prereqInstalled
        Operations --> prereqInstalled
        Support --> prereqInstalled

        High --> prereqInstalled
        Critical --> prereqInstalled

        EnvironmentStrategy(Environments Created)
        AzureDevOps(Azure DevOps Created)
        TechnicalConcepts(Technical Concepts)

        BranchingAndMerging(Branching And Merging) --> TechnicalConcepts

        prereqNo -->EnvironmentStrategy
        EnvironmentStrategy --> AzureDevOps
        AzureDevOps --> TechnicalConcepts

        AA4AM((ALM Accelerator <br/> For Advanced Makers))
        hideComplexity --> AA4AM

        prereqYes -----> AA4AM
        TechnicalConcepts --> AA4AM
        
        AA4AM-DevOps(Azure DevOps)

        Extensions --> AA4AM-DevOps

        AA4AM -->DevelopmentEnvironment(Development Environment)
        DevelopmentEnvironment -->ValidationEnvironment(Validation Environment)
        ValidationEnvironment-->TestEnvironment(Test Environment)
        TestEnvironment--> ProductionEnvironment(Production Environment)
    end

    style aa4am fill:transparent,stroke:green,stroke-width:2px