graph

    subgraph maturity[Power Platform Maturity Level paths to ALM Accelerator for Advanced Makers]
        M{Maturity Level}
        M --> 100((100 - <br/>Initial))
        M ---> 200((200 - <br/>Repetable))
        M ---> 300((300 - <br/>Defined))
        M ---> 400((400 - <br/>Capable))
        M ---> 500((500 - <br/>Efficient))

        100 -.-> 200
        200 -.-> 300
        300 -.-> 400
        400 -.-> 500

        DLP(+ DLP) --> 200
        Environment(+ Environment Strategy) --> 200 

        Automation(+ Automation) --> 300 
        CoE(+ CoE) --> 300

        Champions(+ Champions) --> 400 
        Templates(+ Templates) --> 400 
        MissionCritical(+ Mission Critical) --> 400

        Team(+ Fusion Development Team) --> 500
        Experts(+ Community of Experts) --> 500
    end

    style maturity fill:transparent,stroke:black,stroke-width:2px

    AA4AM((ALM Accelerator <br/>for Advanced Makers))

    300 --> AA4AM
    400 --> AA4AM
    500 --> AA4AM