graph

    subgraph maturity[Maturity]
        M{Maturity Level}
        M --> 100(100 - Initial)
        M --> 200(200 - Repetable)
        M --> 300(300 - Defined)
        
        100 --> DLP
        100 --> Environment

        DLP --> 200
        Environment --> 200

        200 --> Automation
        Automation --> CoE
        CoE --> 300

        300 -.-> 400(400 - Capable)

        Champions(+ Champions) --> 400 
        Templates(+ Templates) --> 400 
        MissionCritical(+ Mission Critical) --> 400

        Team(+ Fusion Development Team) --> Experts(+ Community of Exports)
        Experts(+ Community of Exports) --> 500(500 - Efficient) 

        400 -.-> 500
    end

    style maturity fill:transparent,stroke:black,stroke-width:2px

    AA4AM(ALM Accelerator for Advanced Makers)

    300 --> AA4AM
    400 --> AA4AM
    500 --> AA4AM