name: 🦗[Data Export V2 Product Issue] Bug report
description: File a product blocking issue related to Data Export V2
title: "[Data Export V2 Product Issue]: ISSUE TITLE"
labels: ["coe-starter-kit ", "Data Export V2", "product-gap"]
body:
- type: textarea
  attributes:
    label: Describe the issue
    description: A concise description of what you're experiencing. Please provide as much related information as possible including screenshots, documents, links etc.
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!
      
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
