name: ❓[CoE Starter Kit] Question
description: Ask a question about the CoE Starter Kit
title: "[CoE Starter Kit - QUESTION] QUESTION"
labels: ["coe-starter-kit", "question"]
assignees: Jenefer-Monroe
body:
- type: checkboxes
  attributes:
    label: Does this question already exist in our backlog?
    description: Have you validated that your question is not already in the [backlog](https://github.com/microsoft/coe-starter-kit/issues) or has already been answered in our [wiki](https://github.com/microsoft/coe-starter-kit/wiki/Issue-triage-(CoE-Starter-Kit))?
    options:
      - label: I have checked and confirm this is a new question.
        required: true
- type: textarea
  attributes:
    label: What is your question?
    description: A concise description of what you need to know. Please provide as much related information as possible including screenshots, documents, links etc.
  validations:
    required: true
- type: dropdown
  id: component
  attributes:
    label: What solution are you experiencing the issue with?
    options:
      - Core
      - Governance
      - Nurture
      - Audit Log
      - Innovation Backlog
      - Theming
      - Admin Task Planner
  validations:
    required: false
- type: input
  id: version
  attributes:
    label: What solution version are you using?
    placeholder: "February 2022 or 1.70"
  validations:
    required: false
- type: input
  id: app
  attributes:
    label: What app or flow are you having the issue with?
    placeholder: "Admin - Sync Template v3"
- type: dropdown
  id: component
  attributes:
    label: What method are you using to get inventory and telemetry?
    options:
      - Cloud flows
      - Data Export
  validations:
    required: false
