name: 🐞 [Power Platform Hub] Bug, question or feature ask report
description: File a bug, question or feature ask report for the Power Platform Hub
title: "[Power Platform Hub] ISSUE TITLE"
labels: ["powerplatformhub"]
assignees: manuelap-msft
body:
- type: textarea
  attributes:
    label: Describe your bug, question or feature ask.
    description: A concise description of what issue you are experiencing, what question you have or what feature you would like to see.
  validations:
    required: true
