trigger:
  branches:
    include:
    - main
  paths:
    include:
    - SolutionFolder/* # Replace SolutionFolder with actual folder name in repo
    exclude:
    - SolutionFolder/README.md # Replace SolutionFolder with actual folder name in repo
    
name: 1.0.$(Date:yyyyMMdd)$(Rev:.r)

# TEMPORARY - Currently some third party tasks and some PowerShell scripts which require supplying username/password instead of 
# an Azure DevOps service connection. Using variable groups to store those values for reuse across pipelines.  The variables are:
# - TempUsername
# - TempPassword
# - TestServiceConnection
# - ProdServiceConnection
# The goal is to eliminate the need for any third party tasks and remove or replace PowerShell scripts with Microsoft authored 
# tasks.  This starter kit will serve as a way to help drive and prioritize those tasks.
#
# NOTE: If you want to use different values for these variables, you can remove the variable group and attach them directly to this pipeline.
variables:
- group: global-variable-group
- name: SolutionName
  value: 'SolutionFolder' # Replace SolutionFolder with actual folder name in repo
- name: TestEnvironmentVariables # Values below are for example purposes only.  If you have environment variables, please provide your values.  If no environment variables, please provide value of [] and the task will skip trying to create
  value: | 
    [
      ["prefix_EnvironmentVariableOneName","test-value-to-set"],
      ["prefix_EnvironmentVariableTwoName","100"]
    ]
- name: ProdEnvironmentVariables
  value: | 
    [
      ["prefix_EnvironmentVariableOneName","prod-value-to-set"],
      ["prefix_EnvironmentVariableTwoName","100"]
    ]
- name: TestConnectionReferences # Values below are for example purposes only.  If you have connection references, please provide your values.   If no connection references, please provide value of [] and the task will skip trying to create
  value: | 
    [
      ['prefix_ConnectionReferenceOneName','test-connection-guid'],
      ['prefix_ConnectionReferenceTwoName','test-connection-guid']
    ]
- name: ProdConnectionReferences
  value: | 
    [
      ['prefix_ConnectionReferenceOneName','prod-connection-guid'],
      ['prefix_ConnectionReferenceTwoName','prod-connection-guid']
    ]

stages:
- template: Templates\build-deploy-Solution.yml