# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    cd coe-cli
    npm install
    npm run build
    npm link
    coe --help
    coe aa4am branch \
       -o https://dev.azure.com/pplatform \
       -p coe-starter-kit-azdo \
       -r coe-starter-kit-azdo \
       -d Onboarding \
       -a "$env:SYSTEM_ACCESSTOKEN" \
       -s validation=https://coe-starter-kit-azdo-validation.crm.dynamics.com,test=https://coe-starter-kit-azdo-test.crm.dynamics.com,https://coe-starter-kit-azdo-production.crm.dynamics.com
  displayName: 'npm install and build'
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
