# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none
pr: 
  branches:
    include:
    # Replace the following with actual branch name(s) in your repo for which you want to trigger a build. The assumption here is that you only want to only trigger on a change to a specific branch rather than a change on any branch which would include your working branch for development.'
    - main
    - hotfix
  paths:
    include:
    - coe-cli/

pool:
  vmImage: 'windows-2022'

name: 1.0.$(Date:yyyyMMdd)$(Rev:.r)

variables:
- group: alm-accelerator-variable-group

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- pwsh: |
    $json = (Get-Content ./coe-cli/package.json | ConvertFrom-Json)
    $json.version = "$(Build.BuildNumber)"
    $json | ConvertTo-Json | Set-Content "./coe-cli/package.json"
    node -p "'export const LIB_VERSION = ' + JSON.stringify(require('./coe-cli/package.json').version) + ';'" > coe-cli/src/version.ts
  displayName: 'Set Version Number'
  
- pwsh: |
    npm install
    npm install jest-junit --save-dev
    npm run build
    npm link
  displayName: 'npm install and build'
  workingDirectory: "coe-cli"

- task: Npm@1
  displayName: npm run test
  inputs:
    command: 'custom'
    workingDir: 'coe-cli'
    customCommand: 'run test:ci'

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  condition: succeededOrFailed() # because otherwise we won't know what tests failed
  inputs:
    testResultsFiles: 'coe-cli\junit.xml'

- pwsh: |
    npx pkg -t linux,macos,win ./coe --out-path dist
  displayName: 'Build Executables'
  workingDirectory: "coe-cli"

- pwsh: |
    New-Item -Path "$(Build.ArtifactStagingDirectory)" -Name "Coe-Cli" -ItemType "directory"
    New-Item -Path "$(Build.ArtifactStagingDirectory)\Coe-Cli" -Name "linux" -ItemType "directory"
    Copy-Item ./dist/coe-win.exe $(Build.ArtifactStagingDirectory)\Coe-Cli\coe-cli.exe
    Copy-Item ./dist/coe-linux $(Build.ArtifactStagingDirectory)\Coe-Cli\linux\coe-cli
  displayName: 'Copy executable to Artifact Staging'
  workingDirectory: "coe-cli"

- task: PublishPipelineArtifact@1
  displayName: 'Publish Artifacts'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: drop

- pwsh: |
    git config --global user.email "coebot@outlook.com"
    git config --global user.name "CoEStarterKitBot"

    if(Test-Path -Path "./coe-alm-accelerator-templates-latest") {
        Remove-Item "./coe-alm-accelerator-templates-latest" -Force -Recurse
    }
    New-Item -ItemType "directory" -Name "./coe-alm-accelerator-templates-latest"

    Set-Location "./coe-alm-accelerator-templates-latest"
    git clone https://github.com/microsoft/coe-alm-accelerator-templates.git
    Set-Location "./coe-alm-accelerator-templates"
    $branch = 'coe-cli-update' + (New-Guid).Guid
    git checkout -b $branch "main"
    Copy-Item -Force -Recurse "$(Build.ArtifactStagingDirectory)\Coe-Cli" "./"
    git add --all
    git commit -m "Adding latest coe-cli executables"
    Write-Host "Pushing coe-cli updates"
    git push $(GitAccessUrlTemplates)

    Write-Host "Creating Pull Request"
    Write-Host "##vso[task.setvariable variable=NewBranch;]$branch"
  displayName: 'Create Pull Request in ALM Accelerator Templates'
    
- task: ShaykiAbramczyk.CreatePullRequest.CreatePullRequest.CreatePullRequest@1
  displayName: 'Create Pull Request'
  inputs:
    repoType: GitHub
    githubEndpoint: 'coe-alm-accelerator-templates'
    githubRepository: 'microsoft/coe-alm-accelerator-templates'
    sourceBranch: $(NewBranch)
    targetBranch: main
    title: Automated PR for changes in microsoft/coe-starter-kit/coe-cli build
    description: See https://github.com/microsoft/coe-starter-kit/pulls for details on this PR
    reviewers: 'mikefactorial;RajeevPentyala;jenschristianschroder'
