# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'windows-2022'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- pwsh: |
    npm install
    npm run build
    npm link
    npx pkg -t linux,macos,win ./coe --out-path dist
  displayName: 'npm install and build'
  workingDirectory: "coe-cli"

- pwsh: |
    Copy-Item ./dist/coe-win.exe $(Build.ArtifactStagingDirectory)\coe-cli.exe
    Copy-Item ./dist/coe-linux $(Build.ArtifactStagingDirectory)\coe-cli
  displayName: 'Copy executable to Artifact Staging'
  workingDirectory: "coe-cli"

- task: PublishPipelineArtifact@1
  displayName: 'Publish Artifacts'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: drop
