FROM node:latest AS base
WORKDIR /coe-cli
ADD ./src ./src
ADD ./test ./test
ADD ./coe ./coe
ADD ./config ./config
ADD ./jest.config.js ./jest.config.js
ADD ./package.json ./package.json
ADD ./tsconfig.json ./tsconfig.json
RUN npm install && npm run build && npm link
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash 

CMD ["bash"]