FROM node:latest AS base
WORKDIR /coe-cli
ADD ./src ./src
ADD ./test ./test
ADD ./coe ./coe
ADD ./config ./config
ADD ./scripts ./scripts
ADD ./jest.config.js ./jest.config.js
ADD ./package.json ./package.json
ADD ./tsconfig.json ./tsconfig.json
RUN npm install && npm run build && npm link
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash 
RUN az extension add --upgrade -n azure-devops

# https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7.1
# Install system components
RUN apt-get update
RUN apt-get install -y curl gnupg apt-transport-https

# Import the public repository GPG keys
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -

# Register the Microsoft Product feed
RUN sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-debian-stretch-prod stretch main" > /etc/apt/sources.list.d/microsoft.list'

# Update the list of products
RUN apt-get update

# Install PowerShell
RUN apt-get install -y powershell

CMD ["pwsh"]