# This pipeline gets triggered manually or via an API call.  
# It is a general purpose automation that allows you to export a solution from a Dataverse environment and commit it to a git branch.
# It facilitates:
# -Ensuring user can be part of the commit (instead of a generic user), thereby enabling tracking of who made what changes
# -Reuse for any solution in any Dataverse environment

# The following variables need to be set when the pipeline is queued to run:
# Project: The name of the Azure DevOps Project to which we are exporting our solution.
# Repo: The name of the Azure DevOps Repo to which we are exporting our solution.
# Branch: The name of the Azure DevOps Branch in the Repo above to which we are exporting our solution.
# BranchToCreate: The name of the new Azure DevOps Branch to create in the Repo above to which we are exporting our solution (Optional).
# CommitMessage: The commit message for this commit.
# Email: The email of the user performing the commit.
# ServiceConnection: The name of the service connection to Power Platform from which we'll be pulling the solution.
# SolutionName: The name of the solution being exported (i.e. Not the Display Name).
# TriggerSolutionUpgrade: A flag to determine if a subsequent Pull Request will perform an upgrade in the target environment.
# UserName: The Display name of the user performing the commit.
trigger: none
pr: none

name: export-$(SolutionName)-to-git-branch

variables:
- group: global-variable-group

pool:
  vmImage: 'windows-2019'

steps:

# Checkout Pipelines
- checkout: self
  path: 'PipelineUtils'
  displayName: 'Checkout Pipeline Branch'

# Checkout our Branch
- checkout: git://$(Project)/$(Repo)@$(Branch)
  displayName: 'Checkout Source Branch'

# Other tasks, which use the PowerApps PowerShell cmdlets, need the environment guid.  Setting it for future use.
- template: Templates\export-Solution.yml
  parameters:
    Project: $(Project)
    Repo: $(Repo)
    Branch: $(Branch)
    BranchToCreate: $(BranchToCreate)
    CommitMessage: $(CommitMessage)
    Email: $(Email)
    ServiceConnection: $(ServiceConnection)
    SolutionName: $(SolutionName)
    TriggerSolutionUpgrade: $(TriggerSolutionUpgrade)
    UserName: $(UserName)
