scr_MainSettings As screen:
    LoadingSpinnerColor: =RGBA(0, 120, 212, 1)

    c_mainSettings As groupContainer.verticalAutoLayoutContainer:
        Height: =scr_MainSettings.Height
        LayoutDirection: =LayoutDirection.Vertical
        LayoutMode: =LayoutMode.Auto
        Width: =scr_MainSettings.Width
        ZIndex: =1

        conMainHeader As groupContainer.horizontalAutoLayoutContainer:
            FillPortions: =0
            Height: =150
            LayoutAlignItems: =LayoutAlignItems.Center
            LayoutJustifyContent: =LayoutJustifyContent.Center
            LayoutMinHeight: =100
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            PaddingLeft: =40
            PaddingRight: =Self.PaddingLeft
            PaddingTop: =32
            ZIndex: =1

            conMainHeaderLeft_1 As groupContainer.horizontalAutoLayoutContainer:
                AlignInContainer: =AlignInContainer.SetByContainer
                Height: =100
                LayoutDirection: =LayoutDirection.Vertical
                LayoutJustifyContent: =LayoutJustifyContent.Center
                LayoutMinHeight: =100
                LayoutMinWidth: =250
                LayoutMode: =LayoutMode.Auto
                ZIndex: =3

                Label1_2 As Label:
                    AlignInContainer: =AlignInContainer.Stretch
                    AutoHeight: =true
                    DisplayMode: =DisplayMode.Edit
                    FontSize: =16
                    FontWeight: =FontWeight.Semibold
                    Height: =43
                    LayoutMinHeight: =32
                    LayoutMinWidth: =320
                    PaddingStart: =0  
                    Text: ="Settings"
                    Width: =320
                    X: =35
                    Y: =15
                    ZIndex: =1

                lblMainSubheading_1 As Label:
                    AlignInContainer: =AlignInContainer.Stretch
                    Alignment: =Align.Left
                    AutoHeight: =true
                    DisplayMode: =DisplayMode.Edit
                    FontSize: =11
                    Height: =24
                    LayoutMinHeight: =32
                    LayoutMinWidth: =320
                    Text: ="These settings are applicable across this environment and are specific to the Environment Request Management components."
                    VerticalAlignment: ="middle"
                    Width: =320
                    X: =5
                    Y: =25
                    ZIndex: =2

        c_settings As groupContainer.verticalAutoLayoutContainer:
            LayoutDirection: =LayoutDirection.Vertical
            LayoutMinHeight: =100
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            PaddingLeft: =30
            ZIndex: =2

            Rectangle2_2 As rectangle:
                AlignInContainer: =AlignInContainer.Stretch
                BorderColor: =RGBA(0, 0, 0, 0)
                BorderStyle: =BorderStyle.None
                Fill: =RGBA(204, 204, 204, 1)
                FocusedBorderThickness: =4
                Height: =1
                ZIndex: =2

            gal_settings As gallery.variableTemplateHeightGallery:
                BorderColor: =RGBA(166, 166, 166, 1)
                Height: =Parent.Height
                Items: =col_definitions
                Layout: =Layout.Vertical
                LayoutMinHeight: =287
                LayoutMinWidth: =320
                TemplateSize: =150
                ZIndex: =3

                c_settingRow As groupContainer.verticalAutoLayoutContainer:
                    Height: =100
                    LayoutAlignItems: =LayoutAlignItems.Stretch
                    LayoutDirection: =LayoutDirection.Vertical
                    LayoutMode: =LayoutMode.Auto
                    Width: =Parent.TemplateWidth
                    ZIndex: =1

                    Label1 As label:
                        BorderColor: =RGBA(0, 0, 0, 0)
                        BorderStyle: =BorderStyle.None
                        BorderThickness: =2
                        Color: =RGBA(51, 51, 51, 1)
                        DisabledBorderColor: =RGBA(0, 0, 0, 0)
                        DisabledColor: =RGBA(166, 166, 166, 1)
                        FocusedBorderThickness: =4
                        Font: =Font.'Segoe UI'
                        FontWeight: =FontWeight.Semibold
                        Size: =11
                        Text: =ThisItem.'Display Name'
                        ZIndex: =1

                    Label5 As label:
                        AutoHeight: =true
                        BorderColor: =RGBA(0, 0, 0, 0)
                        BorderStyle: =BorderStyle.None
                        BorderThickness: =2
                        Color: =RGBA(51, 51, 51, 1)
                        DisabledBorderColor: =RGBA(0, 0, 0, 0)
                        DisabledColor: =RGBA(166, 166, 166, 1)
                        FocusedBorderThickness: =4
                        Font: =Font.'Segoe UI'
                        Height: =30
                        Size: =11
                        Text: =ThisItem.Description
                        ZIndex: =2

                    lbl_variableValue As label:
                        BorderColor: =RGBA(0, 0, 0, 0)
                        BorderStyle: =BorderStyle.None
                        BorderThickness: =2
                        Color: =RGBA(51, 51, 51, 1)
                        DisabledBorderColor: =RGBA(0, 0, 0, 0)
                        DisabledColor: =RGBA(166, 166, 166, 1)
                        FocusedBorderThickness: =4
                        Font: =Font.'Segoe UI'
                        Size: =11
                        Text: =If(tgl_setting_1.Checked, "yes", "no")
                        Visible: =false
                        ZIndex: =3

                    tgl_setting_1 As Toggle:
                        Checked: =First(ThisItem.'Environment Variable Values').Value = "yes"
                        DisplayMode: =DisplayMode.Edit
                        Height: =32
                        LayoutMinHeight: =32
                        LayoutMinWidth: =160
                        OnCheck: |
                            =UpdateContext({ var_initialValue: First(ThisItem.'Environment Variable Values').Value = "yes" });
                            UpdateContext({ var_newValue: Self.Checked });
                            
                            Patch( 'Environment Variable Values', {
                                Value: lbl_variableValue.Text,
                                'Schema Name': ThisItem.'Schema Name'
                            });
                            
                            If( var_initialValue <> var_newValue,
                            
                                IfError(
                                    Notify("Successfully updated " & ThisItem.'Display Name' & " environment variable value to " & lbl_variableValue.Text, NotificationType.Success);
                                    ,
                                    Notify("An error occured when updating the environment variable value. Try updating manually to complete the task.", NotificationType.Error)
                                )
                            );
                        PaddingStart: =5
                        Width: =160
                        X: =0
                        Y: =0
                        ZIndex: =5

