admin_environmentdeleted: =If(admin_Environment.admin_environmentdeleted = admin_environment_admin_admin_environment_environmentdeleted.'1', true, false)
admin_percentusedofapproved: =If(IsBlank(admin_approvedcapacity), 0, If(admin_approvedcapacity = 0, 100, (admin_actualconsumption/admin_approvedcapacity)*100))
