FROM node:latest
# Example Build / Run (inside pwsh)
# docker build -t cli-mdbook .
# $current = $pwd.Path
# docker run -it --rm -v ${current}:/docs cli-mdbook
WORKDIR /docs
RUN npm i markdown-spellcheck -g
RUN npm i html-pdf -g
RUN apt update
RUN apt install chromium poppler-utils -y
CMD ["/docs/build.sh"]
