FROM rust
# Example Build / Run (inside pwsh)
# docker build -t cli-mdbook .
# $current = $pwd.Path
# docker run -it --rm -v ${current}:/docs cli-mdbook
WORKDIR /docs
RUN cargo install --version 0.3.7 mdbook
RUN cargo install mdbook-epub
RUN apt update
# librsvg2-bin required for rsvg2pdf  
# poppler-utils is required for pdfunite
# texlive is required for pdflatex
RUN apt-get install pandoc librsvg2-bin poppler-utils texlive -y
CMD ["/docs/build.sh"]
