# Pipeline to create a Github release for the ALM Accelerator for Advanced Makers solution
parameters:
- name: ReleaseMonthNumber
  type: number
- name: ReleaseYearNumber
  type: number

trigger: none
pr: none
resources:
  repositories:
  - repository: PipelineRepo  # repository name (DO NOT CHANGE THIS VALUE) 
    type: github
    ref: vnext # MODEBUG If your pipeline templates are in a branch other than the default branch specify the branch here. Otherwise the default branch will be used by default.
    endpoint: coe-starter-kit # Specifies the GitHub service connection for this setup.
    name: Microsoft/coe-alm-accelerator-templates  #This is the name of the repo in the current project in Azure Devops that has the pipeline templates. If the repo is in a different project you can specify the project and repo using the format ProjectContainingTheBuildTemplates/RepositoryContainingTheBuildTemplates (https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#type)
pool:
  vmImage: 'windows-2019'

variables:
- group: global-variable-group

steps:
# Download the artifacts from the latest deployment of ALMAcceleratorForAdvancedMakers to production.
- task: DownloadPipelineArtifact@2
  inputs:
    source: 'specific'
    project: 'coe-starter-kit-github'
    pipeline: '245' #ALMAcceleratorForAdvancedMakers buildId
    runVersion: 'latest'
    patterns: '**/ALMAcceleratorForAdvancedMakers*.zip'
  displayName: 'Download ALMAcceleratorForAdvancedMakers solution'

# Download the artifacts from the latest deployment of the ALMAcceleratorSampleSolution to production.
- task: DownloadPipelineArtifact@2
  inputs:
    source: 'specific'
    project: 'coe-starter-kit-github'
    pipeline: '125' #ALMAcceleratorSampleSolution buildId
    runVersion: 'latest'
    patterns: '**/ALMAcceleratorSampleSolution*.zip'
  displayName: 'Download ALMAcceleratorSampleSolution solutions'

- powershell: |
    New-Item -Path $(Pipeline.Workspace)\releaseassets -ItemType Directory
    $compress = @{
      Path = '$(Pipeline.Workspace)\drop\*managed.zip'
      CompressionLevel = 'Fastest'
      DestinationPath = '$(Pipeline.Workspace)\releaseassets\ALMAcceleratorForAdvancedMakers.zip'
    }
    Compress-Archive @compress

    Copy-Item '$(Pipeline.Workspace)\drop\ALMAcceleratorFor*managed.zip' -Destination '$(Pipeline.Workspace)\releaseassets'
    Remove-Item '$(Pipeline.Workspace)\drop\*managed.zip'
    
    $compress = @{
      Path = '$(Pipeline.Workspace)/drop/ALMAccelerator*.zip'
      CompressionLevel = 'Fastest'
      DestinationPath = '$(Pipeline.Workspace)\releaseassets\ALMAcceleratorForAdvancedMakers-Unmanaged.zip'
    }
    Compress-Archive @compress
    Copy-Item '$(Pipeline.Workspace)\drop\ALMAcceleratorSample*.zip' -Destination '$(Pipeline.Workspace)\releaseassets'
  displayName: 'Package solutions based on managed vs. unmanaged'

- template: Pipelines\Templates\create-release-github.yml@PipelineRepo
  parameters:
    gitHubApiUrl: 'https://api.github.com/repos/microsoft/coe-starter-kit'
    solutionName: 'ALMAcceleratorForAdvancedMakers'
    solutionDisplayName: 'ALM Accelerator For Advanced Makers'
    releaseMonth: ${{parameters.ReleaseMonthNumber}}
    releaseYear: ${{parameters.ReleaseYearNumber}}
    connectionName: 'coe-starter-kit'
    releaseNotesPath: 'CenterofExcellenceResources/Release/Notes/'
    issueClosingComment: 'This issue has been resolved in the latest release. Please upgrade to the latest version to apply this change.'
    isPreRelease: true
