# Pipeline to create a Github release for the ALM Accelerator for Advanced Makers solution
parameters:
- name: ReleaseMonthNumber
  type: number
- name: ReleaseYearNumber
  type: number

trigger: none
pr: none
resources:
  repositories:
  - repository: PipelineRepo  # repository name (DO NOT CHANGE THIS VALUE) 
    type: github
    ref: mochs-aa4am-589 # If your pipeline templates are in a branch other than the default branch specify the branch here. Otherwise the default branch will be used by default.
    endpoint: coe-starter-kit # Specifies the GitHub service connection for this setup.
    name: Microsoft/coe-alm-accelerator-templates  #This is the name of the repo in the current project in Azure Devops that has the pipeline templates. If the repo is in a different project you can specify the project and repo using the format ProjectContainingTheBuildTemplates/RepositoryContainingTheBuildTemplates (https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#type)
  pipelines: # The pipelines specify which pipeline this pipeline will pull artifacts from. In this case we will deploy from the test build's artifacts
    - pipeline: buildPipeline  # pipeline name (DO NOT CHANGE THIS VALUE) 
      source: deploy-prod-ALMAcceleratorForAdvancedMakers # This is the name of the build pipeline that contains the artifacts to be deployed by this pipeline. NOTE: There must be a successful build for this pipeline available in order to run this pipeline

pool:
  vmImage: 'windows-2019'

variables:
- group: global-variable-group

steps:
# Download the artifacts from the latest deployment of CenterofExcellenceAuditComponents to production.
- task: DownloadPipelineArtifact@2
  inputs:
    source: 'specific'
    project: 'coe-starter-kit-github'
    pipeline: '138' #CenterofExcellenceAuditComponents buildId
    runVersion: 'latest'
    patterns: '**/CenterofExcellenceAuditComponents*.zip'
  displayName: 'Download CenterofExcellenceAuditComponents solution'

# Download the artifacts from the latest deployment of the CenterofExcellenceAuditLogs to production.
- task: DownloadPipelineArtifact@2
  inputs:
    source: 'specific'
    project: 'coe-starter-kit-github'
    pipeline: '142' #CenterofExcellenceAuditLogs buildId
    runVersion: 'latest'
    patterns: '**/CenterofExcellenceAuditLogs*.zip'
  displayName: 'Download CenterofExcellenceAuditLogs solutions'

# Download the artifacts from the latest deployment of the CenterofExcellenceCoreComponents to production.
- task: DownloadPipelineArtifact@2
  inputs:
    source: 'specific'
    project: 'coe-starter-kit-github'
    pipeline: '146' #CenterofExcellenceCoreComponents buildId
    runVersion: 'latest'
    patterns: '**/CenterofExcellenceCoreComponents*.zip'
  displayName: 'Download CenterofExcellenceCoreComponents solutions'

# Download the artifacts from the latest deployment of the CenterofExcellenceCoreComponentsTeams to production.
- task: DownloadPipelineArtifact@2
  inputs:
    source: 'specific'
    project: 'coe-starter-kit-github'
    pipeline: '150' #CenterofExcellenceCoreComponentsTeams buildId
    runVersion: 'latest'
    patterns: '**/CenterofExcellenceCoreComponentsTeams*.zip'
  displayName: 'Download CenterofExcellenceCoreComponentsTeams solutions'

# Download the artifacts from the latest deployment of the CenterofExcellenceInnovationBacklog to production.
- task: DownloadPipelineArtifact@2
  inputs:
    source: 'specific'
    project: 'coe-starter-kit-github'
    pipeline: '154' #CenterofExcellenceInnovationBacklog buildId
    runVersion: 'latest'
    patterns: '**/CenterofExcellenceInnovationBacklog*.zip'
  displayName: 'Download CenterofExcellenceInnovationBacklog solutions'

# Download the artifacts from the latest deployment of the CenterofExcellenceNurtureComponents to production.
- task: DownloadPipelineArtifact@2
  inputs:
    source: 'specific'
    project: 'coe-starter-kit-github'
    pipeline: '166' #CenterofExcellenceNurtureComponents buildId
    runVersion: 'latest'
    patterns: '**/CenterofExcellenceNurtureComponents*.zip'
  displayName: 'Download CenterofExcellenceNurtureComponents solutions'

# Download the artifacts from the latest deployment of the ALMAcceleratorforMakers to production.
- task: DownloadPipelineArtifact@2
  inputs:
    source: 'specific'
    project: 'coe-starter-kit-github'
    pipeline: '134' #ALMAcceleratorforMakers buildId
    runVersion: 'latest'
    patterns: '**/ALMAcceleratorforMakers*.zip'
  displayName: 'Download ALMAcceleratorforMakers solutions'

# Download the artifacts from the latest deployment of the Theming to production.
- task: DownloadPipelineArtifact@2
  inputs:
    source: 'specific'
    project: 'coe-starter-kit-github'
    pipeline: '170' #Theming buildId
    runVersion: 'latest'
    patterns: '**/Theming*.zip'
  displayName: 'Download Theming solutions'

- powershell: |
    New-Item -Path $(Pipeline.Workspace)\releaseassets -ItemType Directory
    $compress = @{
      Path = '$(Pipeline.Workspace)\drop\*managed.zip'
      CompressionLevel = 'Fastest'
      DestinationPath = '$(Pipeline.Workspace)\releaseassets\CoEStarterKit.zip'
    }
    Compress-Archive @compress

    Remove-Item $(Pipeline.Workspace)\drop\*managed.zip
    
    $compress = @{
      Path = '$(Pipeline.Workspace)/drop/ALMAccelerator*.zip'
      CompressionLevel = 'Fastest'
      DestinationPath = '$(Pipeline.Workspace)/releaseassets/CoEStarterKit-Unmanaged.zip'
    }
    Compress-Archive @compress
  displayName: 'Prepare release assets'

- template: Pipelines\Templates\create-release-github.yml@PipelineRepo
  parameters:
    solutionName: 'CoEStarterKit'
    solutionDisplayName: 'CoE Starter Kit'
    releaseMonth: ${{parameters.ReleaseMonthNumber}}
    releaseYear: ${{parameters.ReleaseYearNumber}}
    connectionName: 'coe-starter-kit'
    releaseNotesPath: 'CenterofExcellenceResources/Release/Notes/'
    isPreRelease: true