# Pipeline to create a Github release for the ALM Accelerator for Advanced Makers solution
parameters:
- name: ReleaseMonthNumber
  type: number
- name: ReleaseYearNumber
  type: number
- name: CloseMilestoneIssues
  type: boolean
  default: false

trigger: none
pr: none
resources:
  repositories:
  - repository: PipelineRepo  # repository name (DO NOT CHANGE THIS VALUE) 
    type: github
    ref: main # If your pipeline templates are in a branch other than the default branch specify the branch here. Otherwise the default branch will be used by default.
    endpoint: coe-starter-kit # Specifies the GitHub service connection for this setup.
    name: Microsoft/coe-alm-accelerator-templates  #This is the name of the repo in the current project in Azure Devops that has the pipeline templates. If the repo is in a different project you can specify the project and repo using the format ProjectContainingTheBuildTemplates/RepositoryContainingTheBuildTemplates (https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#type)
pool:
  vmImage: 'windows-2019'

variables:
- group: alm-accelerator-variable-group

steps:
# Download the artifacts from the latest deployment of CenterofExcellenceAuditComponents to production.
- task: DownloadPipelineArtifact@2
  inputs:
    source: 'specific'
    project: 'coe-starter-kit-github'
    pipeline: '138' #CenterofExcellenceAuditComponents buildId
    runVersion: 'latest'
    patterns: '**/CenterofExcellenceAuditComponents*.zip'
  displayName: 'Download CenterofExcellenceAuditComponents solution'

# Download the artifacts from the latest deployment of the CenterofExcellenceAuditLogs to production.
- task: DownloadPipelineArtifact@2
  inputs:
    source: 'specific'
    project: 'coe-starter-kit-github'
    pipeline: '142' #CenterofExcellenceAuditLogs buildId
    runVersion: 'latest'
    patterns: '**/CenterofExcellenceAuditLogs*.zip'
  displayName: 'Download CenterofExcellenceAuditLogs solutions'

# Download the artifacts from the latest deployment of the CenterofExcellenceCoreComponents to production.
- task: DownloadPipelineArtifact@2
  inputs:
    source: 'specific'
    project: 'coe-starter-kit-github'
    pipeline: '146' #CenterofExcellenceCoreComponents buildId
    runVersion: 'latest'
    patterns: '**/CenterofExcellenceCoreComponents*.zip'
  displayName: 'Download CenterofExcellenceCoreComponents solutions'

# Download the artifacts from the latest deployment of the CenterofExcellenceCoreComponentsTeams to production.
- task: DownloadPipelineArtifact@2
  inputs:
    source: 'specific'
    project: 'coe-starter-kit-github'
    pipeline: '150' #CenterofExcellenceCoreComponentsTeams buildId
    runVersion: 'latest'
    patterns: '**/CenterofExcellenceCoreComponentsTeams*.zip'
  displayName: 'Download CenterofExcellenceCoreComponentsTeams solutions'

# Download the artifacts from the latest deployment of the CenterofExcellenceInnovationBacklog to production.
- task: DownloadPipelineArtifact@2
  inputs:
    source: 'specific'
    project: 'coe-starter-kit-github'
    pipeline: '154' #CenterofExcellenceInnovationBacklog buildId
    runVersion: 'latest'
    patterns: '**/CenterofExcellenceInnovationBacklog*.zip'
  displayName: 'Download CenterofExcellenceInnovationBacklog solutions'

# Download the artifacts from the latest deployment of the CenterofExcellenceNurtureComponents to production.
- task: DownloadPipelineArtifact@2
  inputs:
    source: 'specific'
    project: 'coe-starter-kit-github'
    pipeline: '166' #CenterofExcellenceNurtureComponents buildId
    runVersion: 'latest'
    patterns: '**/CenterofExcellenceNurtureComponents*.zip'
  displayName: 'Download CenterofExcellenceNurtureComponents solutions'

# Download the artifacts from the latest deployment of the ALMAcceleratorforMakers to production.
- task: DownloadPipelineArtifact@2
  inputs:
    source: 'specific'
    project: 'coe-starter-kit-github'
    pipeline: '134' #ALMAcceleratorforMakers buildId
    runVersion: 'latest'
    patterns: '**/ALMAcceleratorforMakers*.zip'
  displayName: 'Download ALMAcceleratorforMakers solutions'

# Download the artifacts from the latest deployment of the Theming to production.
- task: DownloadPipelineArtifact@2
  inputs:
    source: 'specific'
    project: 'coe-starter-kit-github'
    pipeline: '170' #Theming buildId
    runVersion: 'latest'
    patterns: '**/Theming*.zip'
  displayName: 'Download Theming solutions'

- powershell: |
    New-Item -Path $(Pipeline.Workspace)\releaseassets -ItemType Directory

    New-Item -Path $(Pipeline.Workspace)\assetstaging -ItemType Directory

    Copy-Item '$(Pipeline.Workspace)\drop\*managed.zip' -Destination '$(Pipeline.Workspace)\assetstaging'
    Copy-Item '$(Build.SourcesDirectory)\CenterofExcellenceResources\Release\Collateral\CoEStarterKit\*.*' -Destination '$(Pipeline.Workspace)\assetstaging'

    $compress = @{
      Path = '$(Pipeline.Workspace)\assetstaging\*.*'
      CompressionLevel = 'Fastest'
      DestinationPath = '$(Pipeline.Workspace)\releaseassets\CoEStarterKit.zip'
    }
    Compress-Archive @compress

    Copy-Item '$(Pipeline.Workspace)\drop\*managed.zip' -Destination '$(Pipeline.Workspace)\releaseassets'
    Remove-Item $(Pipeline.Workspace)\drop\*managed.zip -Recurse -Force -Confirm:$false
    Remove-Item $(Pipeline.Workspace)\assetstaging -Recurse -Force -Confirm:$false
    New-Item -Path $(Pipeline.Workspace)\assetstaging -ItemType Directory

    Copy-Item '$(Pipeline.Workspace)/drop/CenterofExcellence*.zip' -Destination '$(Pipeline.Workspace)\assetstaging'
    Copy-Item '$(Pipeline.Workspace)/drop/Theming*.zip' -Destination '$(Pipeline.Workspace)\assetstaging'
    Copy-Item '$(Pipeline.Workspace)/drop/ALMAccelerator*.zip' -Destination '$(Pipeline.Workspace)\assetstaging'
    Copy-Item '$(Build.SourcesDirectory)\CenterofExcellenceResources\Release\Collateral\CoEStarterKit\*.*' -Destination '$(Pipeline.Workspace)\assetstaging'
    
    $compress = @{
      Path = '$(Pipeline.Workspace)\assetstaging\*.*'
      CompressionLevel = 'Fastest'
      DestinationPath = '$(Pipeline.Workspace)/releaseassets/CoEStarterKit-Unmanaged.zip'
    }
    Compress-Archive @compress
  displayName: 'Prepare release assets'

- template: Pipelines\Templates\create-release-github.yml@PipelineRepo
  parameters:
    gitHubApiUrl: 'https://api.github.com/repos/microsoft/coe-starter-kit'
    solutionName: 'CoEStarterKit'
    solutionDisplayName: 'CoE Starter Kit'
    releaseMonth: ${{parameters.ReleaseMonthNumber}}
    releaseYear: ${{parameters.ReleaseYearNumber}}
    connectionName: 'coe-starter-kit'
    releaseNotesPath: 'CenterofExcellenceResources/Release/Notes/'
    issueClosingComment: 'This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.'
    closeIssues: ${{parameters.CloseMilestoneIssues}}
    isPreRelease: false
