#You can use this sample template if you plan to store the pipeline templates in one repo and your pipeline YAML in another. This is useful for when you have multiple repos and don't want to maintain the templates in multiple places.'
resources:
  repositories:
  - repository: PipelineRepo  # repository name (DO NOT CHANGE THIS VALUE) 
    type: github
    ref: vnext # If your pipeline templates are in a branch other than the default branch specify the branch here. Otherwise the default branch will be used by default.
    endpoint: coe-starter-kit # Specifies the GitHub service connection for this setup.
    name: Microsoft/coe-alm-accelerator-templates  #This is the name of the repo in the current project in Azure Devops that has the pipeline templates. If the repo is in a different project you can specify the project and repo using the format ProjectContainingTheBuildTemplates/RepositoryContainingTheBuildTemplates (https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#type)
trigger: none
pr: 
  branches:
    include:
    # Replace the following with actual branch name(s) in your repo for which you want to trigger a build. The assumption here is that you only want to only trigger on a change to a specific branch rather than a change on any branch which would include your working branch for development.'
    - CenterofExcellenceAuditLogs
  paths:
# Replace 'SolutionFolderInBranch' with actual folder name in repo (i.e. this will be the folder that contains your unpacked solution. In the case where you are using a repo per solution you may not need to specify this value)
    include: # Add any additional paths to include (e.g. SampleSolutionName/PCFControls etc.)
    - CenterofExcellenceAuditLogs/SolutionPackage/ # Replace SolutionFolder with actual folder name in repo
    
name: 1.50.$(Date:yyyyMMdd)$(Rev:.r)

# NOTE: If you want to use different values for these variables, you can remove the variable group and attach them directly to this pipeline. The group specified below is a variable group defined in the Library for the Pipelines
variables:
- group: global-variable-group
- name: SolutionName
  value: 'CenterofExcellenceAuditLogs' #Replace with the actual name of the solution you are building. (NOTE: Not the Display Name)

stages:
- template: Pipelines\Templates\build-deploy-Solution-To-Environment.yml@PipelineRepo #The @PipelineRepo tells the pipeline where to look for the templates based on the name of the repo you specified above
